from __future__ import annotations
import re
import logging
from pathlib import Path

log = logging.getLogger(__name__)

# Explicit route: get '/users', to: 'users#index'
_EXPLICIT_ROUTE_RE = re.compile(
    r"""(get|post|put|patch|delete)\s+["']([^"']+)["']""",
    re.IGNORECASE,
)

# resources :users  /  resource :session
_RESOURCE_RE = re.compile(
    r"""(resources?)\s+:(\w+)""",
    re.IGNORECASE,
)

# namespace :api do  /  scope '/v1' do
_NAMESPACE_RE = re.compile(
    r"""namespace\s+:(\w+)\s+do""",
    re.IGNORECASE,
)
_SCOPE_RE = re.compile(
    r"""scope\s+["']([^"']+)["']\s+do""",
    re.IGNORECASE,
)

# Path params like :id, :user_id
_PATH_PARAM_RE = re.compile(r":(\w+)")

# Standard RESTful actions generated by `resources`
_RESOURCES_ROUTES = [
    ("GET",    "/{name}",            "index"),
    ("POST",   "/{name}",            "create"),
    ("GET",    "/{name}/new",        "new"),
    ("GET",    "/{name}/:id",        "show"),
    ("PUT",    "/{name}/:id",        "update"),
    ("PATCH",  "/{name}/:id",        "update"),
    ("DELETE", "/{name}/:id",        "destroy"),
    ("GET",    "/{name}/:id/edit",   "edit"),
]

# Singular resource (no :id-based index)
_RESOURCE_ROUTES = [
    ("GET",    "/{name}/new",  "new"),
    ("POST",   "/{name}",     "create"),
    ("GET",    "/{name}",     "show"),
    ("PUT",    "/{name}",     "update"),
    ("PATCH",  "/{name}",     "update"),
    ("DELETE", "/{name}",     "destroy"),
    ("GET",    "/{name}/edit", "edit"),
]


class RailsParser:
    """Parse Rails config/routes.rb route definitions."""

    def parse(self, source_path: str) -> list:
        from ..source_discovery import DiscoveredEndpoint
        endpoints: list[DiscoveredEndpoint] = []

        root = Path(source_path)
        route_files = list(root.rglob("config/routes.rb"))
        route_files.extend(root.rglob("config/routes/**/*.rb"))

        for filepath in route_files:
            try:
                content = filepath.read_text(errors="ignore")
                endpoints.extend(self._parse_file(str(filepath), content))
            except Exception as e:
                log.debug("[RailsParser] Error reading %s: %s", filepath, e)

        return endpoints

    def _parse_file(self, filepath: str, content: str) -> list:
        from ..source_discovery import DiscoveredEndpoint
        endpoints: list[DiscoveredEndpoint] = []
        lines = content.split("\n")

        # Track namespace/scope nesting via a prefix stack.
        # We do a line-by-line scan counting `do` blocks.
        prefix_stack: list[str] = []
        block_depth: list[int] = []  # depth at which each prefix was pushed

        depth = 0

        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            # Skip comments and blank lines
            if stripped.startswith("#") or not stripped:
                continue

            # Detect namespace opening
            ns_match = _NAMESPACE_RE.search(stripped)
            if ns_match:
                prefix_stack.append("/" + ns_match.group(1))
                depth += 1
                block_depth.append(depth)
                continue

            # Detect scope opening
            sc_match = _SCOPE_RE.search(stripped)
            if sc_match:
                prefix = sc_match.group(1)
                if not prefix.startswith("/"):
                    prefix = "/" + prefix
                prefix_stack.append(prefix)
                depth += 1
                block_depth.append(depth)
                continue

            # Track generic `do` blocks (that aren't namespace/scope)
            if re.search(r"\bdo\b", stripped):
                depth += 1

            # Track `end` blocks
            if re.search(r"\bend\b", stripped):
                if block_depth and depth == block_depth[-1]:
                    prefix_stack.pop()
                    block_depth.pop()
                depth = max(0, depth - 1)
                continue

            current_prefix = "".join(prefix_stack)

            # Explicit routes: get '/path', to: 'controller#action'
            for match in _EXPLICIT_ROUTE_RE.finditer(stripped):
                method = match.group(1).upper()
                path = match.group(2)
                if not path.startswith("/"):
                    path = "/" + path
                full_path = current_prefix + path
                params = _PATH_PARAM_RE.findall(full_path)
                endpoints.append(DiscoveredEndpoint(
                    path=full_path,
                    method=method,
                    framework="rails",
                    source_file=filepath,
                    params=params,
                    param_type="path" if params else "query",
                    line_number=i,
                ))

            # Resource routes: resources :users / resource :session
            for match in _RESOURCE_RE.finditer(stripped):
                keyword = match.group(1).lower()
                name = match.group(2)
                templates = _RESOURCES_ROUTES if keyword == "resources" else _RESOURCE_ROUTES

                for method, path_template, _action in templates:
                    path = path_template.format(name=name)
                    full_path = current_prefix + path
                    params = _PATH_PARAM_RE.findall(full_path)
                    endpoints.append(DiscoveredEndpoint(
                        path=full_path,
                        method=method,
                        framework="rails",
                        source_file=filepath,
                        params=params,
                        param_type="path" if params else "query",
                        line_number=i,
                    ))

        return endpoints
